[package]
name = "testlua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.8.0-beta.4", features = ["luajit52", "vendored"] }
libloading = "0.7"
